### ISSUE TITLE
Getting a curved point cloud and no laserscan for flat wall

### ISSUE THREAD

**Issue by KaranManghi** [ros-perception/pointcloud_to_laserscan#39] opened 2020-05-27 02:20 UTC
Hi,
   I am getting a curved point cloud for some reason for some scenes even though there are no curved objects. I used the exact same parameters as shown in the pointcloud_to_laserscan_node.cpp. I am using a RealSense camera. Also, when pointed to a wall, it does not show any laserscan. The wall might be at a distance of a meter. 
Kindly help me...

Thank you..

Regards,
Karan Manghi

**Comment by paulbovbel** [comment] 2020-06-05 13:20
Hi @KaranManghi, this kind of thing might be better suited for answers.ros.org, since it's not a bug. You should post your configuration there. Feel free to link to the question here, but I'll close the issue in the meantime.

**Closed as completed by paulbovbel** 2020-06-05 13:20 UTC

**Comment by KaranManghi** [comment] 2020-06-24 01:36
Got it.... Thanks @paulbovbel
