### ISSUE TITLE
whi i can't build for "catkin_make"

### ISSUE THREAD

**Issue by xiaohuozi-code** [ros-perception/pointcloud_to_laserscan#55] opened 2021-05-09 10:36 UTC
The error is ROS1 recognize "pointcloud_to_laserscan" as cmake package.\
how can i solve this problem?

**Comment by hidmic** [comment] 2021-05-31 14:09
@xiaohuozi-code it is a bit unclear to me what the problem is. Additional platform information plus means to reproduce the problem would help a lot.

Having said that, since this is not an issue but a question, I'll close it and encourage you to go check http://answers.ros.org/. There you may engage with the broader ROS community, and the answers you are after will be available for everyone else to see in the future (as opposed to getting lost in this ticket once it is closed). Feel free to tag me there too.

**Closed as completed by hidmic** 2021-05-31 14:09 UTC
